### ISSUE TITLE
Incorrect error message "Identifier 'foo' is not initialized" for variable inside OpenQASM subroutine

### ISSUE THREAD

**Issue by rmshaffer** [aws/amazon-braket-default-simulator-python#156]
**Describe the bug**
In specific cases (see below), a variable which is properly initialized in the OpenQASM program is encountering an error message about being uninitialized when attempting to run the code using the default simulator.

**To reproduce**
The following code snippet reproduces the bug:

```
from braket.devices import LocalSimulator
from braket.ir.openqasm import Program
qasm = '''
OPENQASM 3.0;
def foo() -> bit {
    h q[0];
    bit i;
    i = measure q[0];
    return i;
}
qubit[10] q;
foo();
'''
LocalSimulator().run(Program(source=qasm), shots=5).result()
```

This produces the error:
```
File ~\lib\site-packages\braket\default_simulator\openqasm\interpreter.py:223, in Interpreter._(self, node)
    221     return builtin_constants[node.name]
    222 if not self.context.is_initialized(node.name):
--> 223     raise NameError(f"Identifier '{node.name}' is not initialized.")
    224 return self.context.get_value_by_identifier(node)

NameError: Identifier 'i' is not initialized.
```

**Expected behavior**
No error, the program should run correctly, since `i` is initialized with a `measure` statement.

Note that this does not happen if I first add an initialization to the declaration statement, e.g. `bit i = 0;`. In that case the program works correctly.

**Screenshots or logs**

**System information**
A description of your system. Please provide:
- **Amazon Braket Python SDK version**: 1.36.2
- **Amazon Braket Python Schemas version**: 1.15.0
- **Amazon Braket Python Default Simulator version**: 1.12.1
- **Python version**: 3.10.9

**Additional context**

**Comment by ajberdy** [comment]
This is expected today. Currently, Braket doesn't handle measurement statements explicitly in the local simulator, as all quantum simulation happens after the OpenQASM interpretation.

**Comment by zmohammad01** [comment]
@rmshaffer Were you able to get a resolution on this?

**Comment by rmshaffer** [comment]
@zmohammad01 it sounds like this is behaving as expected in the `main` branch, so I'm fine closing this issue. (To note - the behavior is working correctly in the `mcm-sim` branch, where support for measurement statements has been added.)
