### ISSUE TITLE
Numerical issue with the local AHS simulator

### ISSUE THREAD

**Issue by balewski** [aws/amazon-braket-default-simulator-python#168]
**Describe the bug**
Braket emulator crashes  for a system of 10 atoms, with the error:
  File "/usr/local/lib/python3.10/dist-packages/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_helpers.py", line 566, in _apply_hamiltonian
    output_register += (rabi_coef[index_time] / 2) * rabi_op.dot(input_register)
IndexError: index 400 is out of bounds for axis 0 with size 400

**To Reproduce**
execute attached demonstrator as-is. 
https://bitbucket.org/balewski/quantummind/src/master/QuEra/python/issues/issue1_10atom_crash.py
It will crash in 5 seconds.

But if you reduce the number of atoms in line 74 to 9
 nAtom=9
all works fine.

**Expected behavior**
program should simulate up to nAtom=16

**System information (please complete the following information as applicable):**
$ pip3 list |grep braket
amazon-braket-default-simulator 1.14.0
amazon-braket-schemas           1.17.0
amazon-braket-sdk               1.39.1

  - Working Environment: podman image running locally

**Comment by shpface** [comment]
Thanks for the bug report. I have transferred the issue to the default simulator repository as that is where the bug is. There seems to be an issue with the usage of the ode integrator from scipy. We will look into the source of the bug.

**Comment by shpface** [comment]
Hi Jan, this bug is due to the integrator taking intermediate steps outside of the range of interpolated values that are computed before the integration starts. I'll take a look at what needs to be changed to correct this error. In the meantime, can you try using `device.run(..., solver_method="bdf")` to select a different integration method and see if that one avoids this bug?

**Comment by balewski** [comment]
Hi Stephen,
yes, I confirm changing solver avoids this crash.
Now I can run my simulations on a bigger system. It is a big help!
Thank you for investigating it
Jan

**Comment by guomanmin** [comment]
This issue seems resolved, closing
