### ISSUE TITLE
NotImplementedError: Instruction targets=[0, 1] type=<Type.ecr: 'ecr'> not recognized

### ISSUE THREAD

**Issue by epelofske-LANL** [aws/amazon-braket-default-simulator-python#79]
**Describe the bug**
The ECR gate does not work with LocalSimulator due to a NotImplementedError:

NotImplementedError: Instruction targets=[0, 1] type=<Type.ecr: 'ecr'> not recognized

**System information**
A description of your system. Please provide:
- **Amazon Braket Python SDK version**: `amazon-braket-sdk==1.16.0`
- **Amazon Braket Python Schemas version**: `amazon-braket-schemas==1.7.2`
- **Amazon Braket Python Default Simulator version**: `amazon-braket-default-simulator==1.5.0`
- **Python version**: `Python 3.9.7`

**Comment by kshitijc** [comment]
ECR gate is now available in [v1.6.2](https://github.com/aws/amazon-braket-default-simulator-python/releases/tag/v1.6.2) of amazon-braket-default-simulator-python.
